CREATE TABLE IF NOT EXISTS connections (
  id SERIAL PRIMARY KEY,
  time_stamp TIMESTAMP DEFAULT NULL,
  ip VARCHAR(15) DEFAULT NULL,
  remote_port INTEGER DEFAULT NULL,
  request VARCHAR(6) DEFAULT NULL,
  url SMALLINT DEFAULT NULL,
  operation SMALLINT DEFAULT NULL,
  file SMALLINT DEFAULT NULL,
  query SMALLINT DEFAULT NULL,
  user_agent SMALLINT DEFAULT NULL,
  local_host VARCHAR(15) DEFAULT NULL,
  local_port INTEGER DEFAULT NULL,
  sensor SMALLINT DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS time_idx ON connections (time_stamp);
CREATE INDEX IF NOT EXISTS ip_idx ON connections (ip);
CREATE INDEX IF NOT EXISTS ip2_idx ON connections (time_stamp, ip);

CREATE TABLE IF NOT EXISTS urls (
  id SERIAL PRIMARY KEY,
  path VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS operations (
  id SERIAL PRIMARY KEY,
  op_name VARCHAR(63) NOT NULL
);

CREATE TABLE IF NOT EXISTS files (
  id SERIAL PRIMARY KEY,
  filesize INTEGER DEFAULT NULL,
  filename VARCHAR(255) DEFAULT NULL,
  hash VARCHAR(66)
);

CREATE UNIQUE INDEX IF NOT EXISTS hash_idx ON files (hash);

CREATE TABLE IF NOT EXISTS queries (
  id SERIAL PRIMARY KEY,
  query JSONB
);

CREATE TABLE IF NOT EXISTS user_agents (
  id SERIAL PRIMARY KEY,
  user_agent VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS sensors (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) DEFAULT NULL
);

CREATE UNIQUE INDEX name_idx ON sensors (name);

CREATE TABLE IF NOT EXISTS geolocation (
  id SERIAL PRIMARY KEY,
  ip VARCHAR(15) DEFAULT NULL,
  country_name VARCHAR(45) DEFAULT '',
  country_iso_code VARCHAR(2) DEFAULT '',
  city_name VARCHAR(128) DEFAULT '',
  org VARCHAR(128) DEFAULT '',
  org_asn INTEGER DEFAULT NULL
);

CREATE UNIQUE INDEX ip3_idx ON geolocation (ip);
